;METADATA=(Diff=true, UseCommands=true)

[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=True
bDynamicReplication=False
InvalidTagCharacters="\"\',"
+CommonlyReplicatedTags=State.AimDownSights
+CommonlyReplicatedTags=State.AimDownSights.Removal
+CommonlyReplicatedTags=State.Sprinting
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagRedirects=(OldTagName="Event.Combat.Hit",NewTagName="Event.Combat.MeleeHit")
+GameplayTagList=(Tag="Ability.AimDownSights",DevComment="")
+GameplayTagList=(Tag="Ability.Attack",DevComment="")
+GameplayTagList=(Tag="Ability.Attack.Air",DevComment="")
+GameplayTagList=(Tag="Ability.Attack.BareHand",DevComment="")
+GameplayTagList=(Tag="Ability.Attack.Launcher",DevComment="")
+GameplayTagList=(Tag="Ability.Attack.Melee",DevComment="")
+GameplayTagList=(Tag="Ability.Jump",DevComment="")
+GameplayTagList=(Tag="Ability.NotCanceledByStun",DevComment="")
+GameplayTagList=(Tag="Ability.Skill.Ability1",DevComment="")
+GameplayTagList=(Tag="Ability.Skill.Ability2",DevComment="")
+GameplayTagList=(Tag="Ability.Skill.Ability3",DevComment="")
+GameplayTagList=(Tag="Ability.Skill.Ability4",DevComment="")
+GameplayTagList=(Tag="Ability.Skill.Ability5",DevComment="")
+GameplayTagList=(Tag="Ability.Sprint",DevComment="")
+GameplayTagList=(Tag="Activation.Fail.BlockedByTags",DevComment="")
+GameplayTagList=(Tag="Activation.Fail.CantAffordCost",DevComment="")
+GameplayTagList=(Tag="Activation.Fail.IsDead",DevComment="")
+GameplayTagList=(Tag="Activation.Fail.MissingTags",DevComment="")
+GameplayTagList=(Tag="Activation.Fail.Networking",DevComment="")
+GameplayTagList=(Tag="Activation.Fail.OnCooldown",DevComment="")
+GameplayTagList=(Tag="Cooldown.Skill.Ability5",DevComment="")
+GameplayTagList=(Tag="Data.Damage",DevComment="")
+GameplayTagList=(Tag="Data.Stamina",DevComment="")
+GameplayTagList=(Tag="Effect.Hero.PassiveArmor",DevComment="")
+GameplayTagList=(Tag="Effect.HitReact.Back",DevComment="")
+GameplayTagList=(Tag="Effect.HitReact.Front",DevComment="")
+GameplayTagList=(Tag="Effect.HitReact.Left",DevComment="")
+GameplayTagList=(Tag="Effect.HitReact.Right",DevComment="")
+GameplayTagList=(Tag="Effect.RemoveOnDeath",DevComment="")
+GameplayTagList=(Tag="Event.Combat",DevComment="")
+GameplayTagList=(Tag="Event.Combat.AirDownFinish",DevComment="")
+GameplayTagList=(Tag="Event.Combat.AttackInput",DevComment="")
+GameplayTagList=(Tag="Event.Combat.CombatWindow",DevComment="")
+GameplayTagList=(Tag="Event.Combat.CombatWindow.Close",DevComment="")
+GameplayTagList=(Tag="Event.Combat.CombatWindow.Open",DevComment="")
+GameplayTagList=(Tag="Event.Combat.HeavyInput",DevComment="")
+GameplayTagList=(Tag="Event.Combat.MeleeHit",DevComment="")
+GameplayTagList=(Tag="Event.LightInput",DevComment="")
+GameplayTagList=(Tag="Event.Montage.EndAbility",DevComment="")
+GameplayTagList=(Tag="Event.Montage.SpawnProjectile",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Hero.FireGun.Impact",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Hero.Sprint",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Shared.MeleeImpact",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Shared.Poison",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Shared.Stun",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Shared.SwordSlash",DevComment="")
+GameplayTagList=(Tag="State.AimDownSights.Removal",DevComment="")
+GameplayTagList=(Tag="State.Airborne",DevComment="")
+GameplayTagList=(Tag="State.AirComboUsed",DevComment="")
+GameplayTagList=(Tag="State.Attacking",DevComment="")
+GameplayTagList=(Tag="State.CombatMode",DevComment="")
+GameplayTagList=(Tag="State.CombatMode.BareHand",DevComment="")
+GameplayTagList=(Tag="State.ComboWindow",DevComment="")
+GameplayTagList=(Tag="State.Dead",DevComment="")
+GameplayTagList=(Tag="State.Debuff.Poison",DevComment="")
+GameplayTagList=(Tag="State.Debuff.Stun",DevComment="")
+GameplayTagList=(Tag="State.Sprinting",DevComment="")

